### ISSUE TITLE
Tree metadata - use OO

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shawnlaffan/biodiverse#475] opened 2015-03-27 23:02 UTC
```
See issue 474 for details.  
```

Original issue reported on code.google.com by `shawnlaffan` on 22 Jun 2014 at 8:50
* Blocking: #474

**Comment by shawnlaffan** [comment] 2015-04-25 10:39
This is a duplicate of issue #544.  While it was listed later, it applies to more packages.

**Comment by shawnlaffan** [comment] 2015-04-25 10:41
Duplicate of #544

(trying a different approach to merging issues)

**Comment by shawnlaffan** [comment] 2015-04-25 10:42
That doesn't seem to work, so closing again.

**Closed by shawnlaffan** 2015-04-25 10:42 UTC
Labels: auto-migrated, duplicate, Priority-Medium, Type-Enhancement
