### ISSUE TITLE
Basedata - add merge option

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shawnlaffan/biodiverse#424] opened 2015-03-27 23:01 UTC
```
It would be useful if there was the ability to merge two or more basedata 
objects.  

The objects would need to have the same cell sizes and origins for groups and 
labels.  

The results should go into a new basedata since any analyses would be 
invalidated by the addition of data.  


```

Original issue reported on code.google.com by `shawnlaffan` on 28 Nov 2013 at 9:59

**Comment by shawnlaffan** [comment] 2015-06-07 01:57
Closing this issue - it is a duplicate of issue #493.

**Closed by shawnlaffan** 2015-06-07 01:57 UTC
Labels: auto-migrated, duplicate, Priority-Medium, Type-Enhancement
